baseurl:
title: NodeBots Mauritius
subtitle: Learn how to make robots powered by JavaScript and More!
author: rahul thakoor
#simple_search: http://google.com/search
description: The homepage for NodeBots Mauritius Community
name: tufte
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
permalink: /articles/:short_year/:title
timezone: Indian/Mauritius
excerpt_separator: <!--more-->  # you can specify your own separator, of course.
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'UploadToGithub.Rakefile', 'README.md']
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: gvim
git:
  branch: master
transfer:
  command: rsync
  settings: -av
  source: _site/
  #destination: ~/Git/clayh53.github.com/
